### ISSUE TITLE
Bringing back grafana with prometheus dependency

### ISSUE THREAD

**Issue by iamyume** [zeebe-io/zeebe-cluster-helm#104]
It looks like that the chart dependency `prometheus-operator` was replaced by `prometheus` in commit [`2779f16b05632cf6a4fdd87acd7c41bcf0fae332`](https://github.com/zeebe-io/zeebe-cluster-helm/commit/2779f16b05632cf6a4fdd87acd7c41bcf0fae332)

From the `README.md` the prometheus-operator helm chart located at https://github.com/helm/charts/tree/master/stable/prometheus-operator has been deprecated and renamed to [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

The issue with just using the `prometheus` chart, grafana is not included which used to be when `prometheus-operator` was the dependency. Would it be possible to switch out `prometheus` dependency with `kube-prometheus-stack`?

**Comment by salaboy** [comment]
@iamyume that sounds like the right thing to do.. would you mind sending a PR for that?

**Comment by iamyume** [comment]
I can definitely try creating a PR

**Comment by salaboy** [comment]
@iamyume please do and let me know if you face issues.
