### ISSUE TITLE
Expose Zeebe configuration map

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#14]
Would it be possible to define a configuration map on helm installation? Honestly I'm not really familiar with the helm charts.

So for example what we often use is a config like this:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeebe
  labels:
    app: zeebe
data:
  zeebe.cfg.toml: |
    [cluster]
    partitionsCount = 3
    replicationFactor = 3

    [threads]
    cpuThreadCount = 4
    ioThreadCount = 4

    [gateway.cluster]
    requestTimeout = "60s"

    [gateway.monitoring]
    enabled = true

    [data]
    snapshotPeriod = "15m"
    maxSnapshots = "3"

    [[exporters]]
    id = "elasticsearch"
    className = "io.zeebe.exporter.ElasticsearchExporter"

    [exporters.args]
    url = "http://elasticsearch-master-headless:9200"
```

**Comment by salaboy** [comment]
@Zelldon we already have the ConfigMap in the Helm Chart. This ConfigMap is already parameterizable but I wonder if we need more flexibility in there: 
https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/configmap.yaml#L30
Do you see something wrong in the default CM that we are providing in the Helm Charts (besides flexiblitity). 

For some of those parameters that I can see in your example, like:
```
[cluster]
    partitionsCount = 3
    replicationFactor = 3
```

We are already setting those via ENV_VARIABLES into the StatefulSet Pod Spec(https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/statefulset.yaml#L35), so I wonder if we can just get rid of the `zeebe.cfg.toml` file content in the ConfigMap in favor of ENV_VARIABLES for all the values. 

Having different ways to set up configurations for the brokers will make it super confusing for people. If we can standardize with ENV_VARIABLES it will be great :)

**Comment by Zelldon** [comment]
> We are already setting those via ENV_VARIABLES into the StatefulSet Pod Spec(https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/statefulset.yaml#L35), so I wonder if we can just get rid of the zeebe.cfg.toml file content in the ConfigMap in favor of ENV_VARIABLES for all the values.

This will probably not work until we support all configurations via ENV variables in the broker right? Or will you convert env variables in your charts to toml configuration?

> Having different ways to set up configurations for the brokers will make it super confusing for people. If we can standardize with ENV_VARIABLES it will be great :)

Agree, would be nice but this will probably not come before the next zeebe release.

I think it would be much easier for now if we just accept a complete configmap as configuration like:

```
  zeebe.cfg.toml: |
    [cluster]
    partitionsCount = 3
    replicationFactor = 3

    [threads]
    cpuThreadCount = 4
    ioThreadCount = 4

    [gateway.cluster]
    requestTimeout = "60s"

    [gateway.monitoring]
    enabled = true

    [data]
    snapshotPeriod = "15m"
    maxSnapshots = "3"

    [[exporters]]
    id = "elasticsearch"
    className = "io.zeebe.exporter.ElasticsearchExporter"

    [exporters.args]
    url = "http://elasticsearch-master-headless:9200"
```

We normally want to configure snapshot interval, max count etc. Or if we introduce new configurations we just want to test it with different values.
