### ISSUE TITLE
Version of elasticsearch helm chart used is not compatible with k8s version 1.16

### ISSUE THREAD

**Issue by PashCracken** [zeebe-io/zeebe-cluster-helm#4]
Hi,

Version 7.3.0 of elasticsearch helm charts are not compatile with k8s version 1.16. It uses deprecated apiVersions.
Can you please update the version of the elasticsearch helm charts you use from version 7.3.0 to latest. The newer version has updated apiVersion so it will work with newer versions of k8s. 

This issue is currently blocking us from deploying Zeebe to our Kubernetes cluster

Thanks
Jan

**Comment by salaboy** [comment]
@PashCracken thank you for reporting this issue, it is highly appreciated. Did you manually tested Zeebe with that version of the elastic search chart? I will be more than happy to review and release if you provide a PR for the change.

**Comment by salaboy** [comment]
@PashCracken thank you for your PR. it was merged and released already.. version https://github.com/zeebe-io/zeebe-cluster-helm/releases/tag/v0.0.34 contains your changes . 
If you are using the zeebe-full chart the new version pointing to 0.0.34 is -> https://github.com/zeebe-io/zeebe-full-helm/releases/tag/v0.0.18

Can you contact me via pvt message (email: salaboy at camunda or twitter @salaboy ) ? I would like to send you a contributor pack as a gift to you for making these contributions. 
Also please review my comments on the Operate PR: https://github.com/zeebe-io/zeebe-operate-helm/pull/2 so we can merge it asap.

**Comment by salaboy** [comment]
@PashCracken Ok charts released with your changes on Operate as well: 
https://github.com/zeebe-io/zeebe-full-helm/blob/master/dependency-matrix/matrix.md
