### ISSUE TITLE
README is broken

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-cluster-helm#48]
Seems I broke the table of values in the README, sorry :see_no_evil:

**Comment by salaboy** [comment]
that is alright.. I break it all the time.

**Comment by salaboy** [comment]
@npepinpe do you see it broken now?

**Comment by Zelldon** [comment]
Sorry I fixed it already https://github.com/zeebe-io/zeebe-cluster-helm/commit/6cb9cfc08e4b36a7ea4a2c4761b6164404017642
