### ISSUE TITLE
Disabling embedded Gateway doesn't work with newest Zeebe version

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#49]
We wanted to disable the embedded gateway by default but with out latest cfg changes this didn't work.

https://github.com/zeebe-io/zeebe-cluster-helm/blob/6cb9cfc08e4b36a7ea4a2c4761b6164404017642/zeebe-cluster/templates/configmap.yaml#L39

**Comment by salaboy** [comment]
@Zelldon is this a problem on the helm charts?

**Comment by Zelldon** [comment]
Yes since it doesnt use the new cfgs and env variables

**Comment by Zelldon** [comment]
This is outdated
