### ISSUE TITLE
zeebe deployment failing | cp: cannot stat '/exporters/*.jar': No such file or directory

### ISSUE THREAD

**Issue by coolpalani** [zeebe-io/zeebe-cluster-helm#50]
We're getting following error message while deploy zeebe.
Due to this changes [code](https://github.com/zeebe-io/zeebe-cluster-helm/blob/c589c44a60f1f0f29a1bcca23e9fecf90fbc16d7/zeebe-cluster/templates/configmap.yaml#L32)

`kubectl.exe logs pod/workflow-zeebe-0 -n zeebe`
`++ hostname -f`
`+ export ZEEBE_ADVERTISED_HOST=workflow-zeebe-0.workflow-zeebe.zeebe.svc.cluster.local`
`+ ZEEBE_ADVERTISED_HOST=workflow-zeebe-0.workflow-zeebe.zeebe.svc.cluster.local`
`+ export ZEEBE_NODE_ID=0`
`+ ZEEBE_NODE_ID=0`
`+ export ZEEBE_CLUSTER_SIZE=1`
`+ ZEEBE_CLUSTER_SIZE=1`
`+ contactPointPrefix=workflow-zeebe`
`+ contactPoints=`
`+ [[ -z '' ]]`
`+ (( i=0 ))`
`+ (( i<1 ))`
`++ hostname -d`
`+ contactPoints=,workflow-zeebe-0.workflow-zeebe.zeebe.svc.cluster.local:26502`
`+ (( i++ ))`
`+ (( i<1 ))`
`+ export ZEEBE_CONTACT_POINTS=,workflow-zeebe-0.workflow-zeebe.zeebe.svc.cluster.local:26502`
`+ ZEEBE_CONTACT_POINTS=,workflow-zeebe-0.workflow-zeebe.zeebe.svc.cluster.local:26502`
`+ ls -al /exporters/`
`+ cp -a '/exporters/*.jar' /usr/local/zeebe/exporters/`
`total 12`
`drwxrwsrwx. 2 root daemon 4096 Apr  8 14:10 .`
`drwxr-xr-x. 1 root root   4096 Apr  8 14:14 ..`
`cp: cannot stat '/exporters/*.jar': No such file or directory`

**Comment by salaboy** [comment]
@coolpalani thanks for reporting I am working on the fix.. but you can use older versions of the chart if you want

**Comment by salaboy** [comment]
@coolpalani fixed now!
