### ISSUE TITLE
Test Connection pod fails to template properly with Helm 3

### ISSUE THREAD

**Issue by pinkertonpg** [zeebe-io/zeebe-cluster-helm#59]
The test-connection pod fails to apply at all because it ends up as
```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-zeebe-test-connection"
...
```
Applying this against a kubernetes cluster gets you:

```
poddisruptionbudget.policy/elasticsearch-master-pdb created
configmap/test1-zeebe created
service/elasticsearch-master created
service/elasticsearch-master-headless created
service/test1-zeebe-gateway created
service/test1-zeebe created
deployment.apps/test1-zeebe-gateway created
statefulset.apps/elasticsearch-master created
statefulset.apps/test1-zeebe created
pod/test1-mlmap-test created
The Pod "{{ .Release.Name }}-zeebe-test-connection" is invalid: metadata.name: Invalid value: "{{ .Release.Name }}-zeebe-test-connection": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Since we embed templating in values.yaml in `global.zeebe`, I believe you have to tell Helm to explicitly re-template any file we reference that in via `tpl`. This is already done in all other files in this chart, this is the only exception.

**Helm 3 change?**

I'm using Helm 3.2 and I noticed the Zeebe docs reference Helm 2 syntax, so maybe this behavior is slightly different between the two versions?

**Potential fix**
I have a branch that fixes this [here](https://github.com/zeebe-io/zeebe-cluster-helm/compare/master...pinkertonpg:58-fix-test-connection-template?expand=1) that I've confirmed works on my end, happy to PR if that's the appropriate fix.

**Comment by salaboy** [comment]
@pinkertonpg please do submit a PR for that.. as we are aiming for Helm 3 only.. we need to update the docs.. as our current charts were created with Helm 2 and they still work with Helm 2, but I think that the error that you are getting might be because the relase name is not being replaced...
