### ISSUE TITLE
Cannot set custom annotations on the gateway pods

### ISSUE THREAD

**Issue by pinkertonpg** [zeebe-io/zeebe-cluster-helm#65]
The broker StatefulSet template allows you to set `podAnnotations` that end up in the pod template, but the gateway Deployment does not: https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/gateway-deployment.yaml#L19-L23.

This is useful for users wanting to set custom annotations that help power other kube services that do things like metrics, monitoring, and even traffic routing, that would key off of pod annotations.

**Comment by salaboy** [comment]
@pinkertonpg good catch.. and yes.. we need to add those podAnnotations in the gateway as well.. would you mind sending a PR for that?
