### ISSUE TITLE
Unable to configure additional exporters

### ISSUE THREAD

**Issue by rruizperez** [zeebe-io/zeebe-cluster-helm#66]
Hi,

I am trying to get the following tutorial running on my k8s cluster:
[https://zeebe.io/blog/2019/05/exporter-part-1/](url)

However when I add the zeebeCfg field:

> zeebeCfg: |- 
  [[exporters]]
  id = "demo"
  className = "io.zeebe.DemoExporter" 

 

I get:

> Error: YAML parse error on zeebe-full/charts/zeebe/templates/configmap.yaml: error converting YAML to JSON: yaml: line 42: could not find expected ':'

I've tried adding the configuration formatted as yaml:
> exporters:
    - id = demo
      className = io.zeebe.DemoExporter

without luck.

here is the configuration that gets loaded from the broker logs:

> Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local",
      "advertisedPort" : 26501,
      "advertisedAddress" : "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local:26501",
      "address" : "0.0.0.0:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local",
      "advertisedPort" : 26502,
      "advertisedAddress" : "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local:26502",
      "address" : "0.0.0.0:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local",
      "advertisedPort" : 9600,
      "advertisedAddress" : "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local:9600",
      "address" : "0.0.0.0:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "zeebe-zeebe-0.zeebe-zeebe.zeebe.svc.cluster.local:26502", "zeebe-zeebe-1.zeebe-zeebe.zeebe.svc.cluster.local:26502", "zeebe-zeebe-2.zeebe-zeebe.zeebe.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 0,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-zeebe",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "logSegmentSizeInBytes" : 536870912
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "http://elasticsearch-master:9200"
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M"
}

I expect to be able to load custom made exporters in this hel charts.

thank you

**Comment by salaboy** [comment]
@rruizperez hi there.. thanks for reporting this.. I think that you might need to look into ENV variables to set up the exporters now. @npepinpe can you help me out here? I think that you can point us in the right direction with the new changes in 0.23.1. 
This is how we are setting the elasticsearch exporter now: https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/statefulset.yaml#L61

**Comment by rruizperez** [comment]
> @rruizperez hi there.. thanks for reporting this.. I think that you might need to look into ENV variables to set up the exporters now. @npepinpe can you help me out here? I think that you can point us in the right direction with the new changes in 0.23.1.
> This is how we are setting the elasticsearch exporter now: https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/statefulset.yaml#L61

Thank you.

I was aware of how the configuration gets loaded for the elasticsearch exporter, but it seems that there are special ENV variables for just that exporter.

Where can I check the docs on how to configure the ENV variables for custom made exporters?

**Comment by rruizperez** [comment]
nvm, I think I found it on:
[https://docs.zeebe.io/appendix/broker-config-template.html](url)

Thank you

**Comment by npepinpe** [comment]
Just a short note, the Kafka exporter hasn't be updated yet for Zeebe 1.0, and will probably not be before the Helm chart is updated to work with Zeebe 1.0, since I'm maintaining it in my spare time :sweat_smile:

**Comment by steinroe** [comment]
No worries, I am trying to use it with zeebe `0.26.3`. And btw. thanks for the great work on the exporter!

**Comment by steinroe** [comment]
Adding

 ```
 - name: ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH
    value: exporters/zeebe-kafka-exporter.jar
  - name: ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME
    value: io.zeebe.exporters.kafka.KafkaExporter
```

to the environment variables makes zeebe pickup the exporter, but I still cannot figure out how to set the config.

**Comment by steinroe** [comment]
Sorry for the spam, but you can configure the kafka exporter using env variables like this:
```
- name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_PRODUCER_CONFIG
    value: "bootstrap.servers='<your-url>'\nsecurity.protocol=SASL_SSL\nsasl.mechanism=PLAIN\nacks=all\nsasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='<your-user>' password='<your-pw>'"
```
The example is for configuring it to work with confluent, but you can pass any java config.
