### ISSUE TITLE
Set ZEEBE_GATEWAY_CLUSTER_HOST to its hostname or ip

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe-cluster-helm#71]
ZEEBE_GATEWAY_CLUSTER_HOST is currently set to '0.0.0.0'. This cause issues in deployments with Standalone Gateway because the broker tries to communicate with the gateway by sending messages to `0.0.0.0`. 

ZEEBE_GATEWAY_CLUSTER_HOST should be set to an externally reachable IP or hostname.

**Comment by salaboy** [comment]
@npepinpe @Zelldon did something changed about this? I remember that someone did this change maybe in 0.22?

**Comment by npepinpe** [comment]
It was probably something I did when migrating to 0.23.x - should be fixed

**Comment by salaboy** [comment]
@npepinpe @deepthidevaki should we close this? is it fixed?

**Comment by npepinpe** [comment]
The relevant PR was merged so yes :+1:
