### ISSUE TITLE
The latest chart 0.0.106 not working

### ISSUE THREAD

**Issue by xuanzhong** [zeebe-io/zeebe-cluster-helm#73]
The zeebe version 0.23.1 requires application.yaml as the configuration. But the ConfigMap creation of application.yaml is not working properly.  Can you provide a working example for  .values.zeebeCfg? which will be rendered as application.yaml via ToYaml in the zeebe configmap.

**Comment by xuanzhong** [comment]
The issue is resolved by the following code change in templates/configmap.yaml
@@ -37,4 +37,6 @@ data:

     exec /usr/local/zeebe/bin/broker
   application.yaml:
-    {{ toYaml .Values.zeebeCfg }}
+{{- with .Values.zeebeCfg }}
+{{ . | toYaml | indent 4 }}
+{{- end }}

**Comment by salaboy** [comment]
@xuanzhong hi there.. why did you close the issue? did you get it fixed on your side?

**Comment by salaboy** [comment]
@xuanzhong also.. which version of helm are you using?

**Comment by salaboy** [comment]
your suggestion is now applied in 107
