### ISSUE TITLE
Allow setting resource requests/limits on the gateway replicas

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-cluster-helm#74]
Currently the gateway runs with no limits, which may not always be desirable. It should be possible to set resource requests/limits on the gateway as well as the broker.

**Comment by salaboy** [comment]
Are these not working: https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/values.yaml#L72 ?

**Comment by salaboy** [comment]
I totally agree that we need those for the gateway

**Comment by npepinpe** [comment]
These work for the broker stateful set, but are not applied on the gateway deployment.
