### ISSUE TITLE
Explain Java options and reasoning

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#80]
Would be good to know why have the current [JavaOptions](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/values.yaml#L47) and what was the reason to put them at this value.

I'm especially interested in:

```
  -XX:+UseParallelGC
  -XX:MinHeapFreeRatio=5
  -XX:MaxHeapFreeRatio=10
  -XX:MaxRAMPercentage=25.0
  -XX:GCTimeRatio=4
  -XX:AdaptiveSizePolicyWeight=90
```

Because these settings currently seem to make serious problems on deploying Zeebe with one partition, see this issue https://github.com/zeebe-io/zeebe/issues/4664#issuecomment-645325989

@salaboy any ideas ?

**Comment by falko** [comment]
Yes, I have been asked about this by customers as well.

**Comment by Zelldon** [comment]
I assume they are just copied from somewhere. For example here they are listed https://docs.openshift.com/container-platform/3.9/dev_guide/application_memory_sizing.html#encouraging-the-JVM-to-release-unused-memory It seem this configuration makes the GC really aggressive.

**Comment by salaboy** [comment]
@Zelldon @falko we can change these parameters in any way we want, some of these parameters were provided by previous yaml files, copied from other places and never updated since we started.. I am happy to change them all, but I haven't seen any suggestions yet. 
Remember that we started with JDK 8 which required different paramters to make sure that the JVM was aware that it was running inside Docker, but since we moved to JDK 11 those parameters weren't updated..

**Comment by Zelldon** [comment]
Thanks @salaboy I think maybe we should then just use the defaults from the jvm until we tested and found better parameters or we see problems with them. I think we will spent in the future some time to find good new values, but I think for now we should just use defaults. 

We should keep 

```
 -Xmx4g
  -Xms4g
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
```

Because we know that they work with our system and bringing value.

**Comment by npepinpe** [comment]
In the cloud we now also include the `-XX:+ExitOnOutOfMemoryError`, since Zeebe becomes quite unstable when it hits an OOM - should we also include it here?

**Comment by Zelldon** [comment]
Yes I think so. Otherwise the system might in a weird state when the oom's are catched.
