### ISSUE TITLE
Liveness probe should not use ready endpoint

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#9]
Currently the Broker does not support any liveness checks.
The liveness probe should not use the ready endpoint, since it can take up to the configured snapshotInterval to be ready for each partition. 

On Broker start the partitions are recreated and start reprocessing from the last snapshot, this can take several minutes up to the configured snapshotInterval. After all partitions are ready the broker is ready and the ready endpoint will return a good value.

If we use this endpoint as liveness probe k8s will probably kill the pod in a loop, since it is never ready in time. Related to that https://github.com/zeebe-io/zeebe/issues/3600#issuecomment-571914391

**Comment by salaboy** [comment]
@Zelldon that is correct.. for such reason the initial interval is high.. but I will definitely love to see if we can expose one endpoint for that specifically. Is that doable? Can we create an issue? I might be able to work on it with some guidance..

**Comment by Zelldon** [comment]
Unfortunately the start interval is not high enough. We already have an open issue for that. https://github.com/zeebe-io/zeebe/issues/2484 This is an ongoing topic for quite a while, but we have not found any satisfied solution yet.

I while ago I thought about doing this with help of metrics, does this make sense? Do you know how other systems do this? Maybe you can add your input at this topic.

**Comment by salaboy** [comment]
@Zelldon should we remove it for now then? until we have something reliable to trust on the liveness probes? 
In my experience that is why spring boot actuators are super useful. If we have a way in Zeebe to emit an event when everything is started, having an endpoint to externalize that should be super easy. I would go with that. 

Using metrics sounds super complex .. I am not entirely sure about which metrics do you mean exactly and from where are you going to read them, but having an eventing mechanism which can let us know when the broker has done all the init work will be great. Is that something that you see doable?

**Comment by Zelldon** [comment]
> @Zelldon should we remove it for now then? until we have something reliable to trust on the liveness probes?

Yes this would also be my proposal.

> Using metrics sounds super complex .. I am not entirely sure about which metrics do you mean exactly and from where are you going to read them, but having an eventing mechanism which can let us know when the broker has done all the init work will be great. Is that something that you see doable?

This is actually the ready endpoint. It returns only a valid value when the startup phase is done.

**Comment by Zelldon** [comment]
Maybe we can add a start up probe https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

**Comment by salaboy** [comment]
@Zelldon I like startup probes.. because if the `/ready` endpoint is returning 200 after init is done, we should be fine with it. I will give that a try before removing the livenessProbe

**Comment by salaboy** [comment]
@Zelldon, unfortunately, we cannot use the startup probes just yet.. they were introduced too recently (V1.16) to be supported by most Kubernetes installations. In GKE the default is currently V1.13 and you can go to V1.15 max so we will need to wait for that.

**Comment by salaboy** [comment]
Done Zeebe Cluster Helm V0.0.45 doesn't have the livenessProbes: https://github.com/zeebe-io/zeebe-cluster-helm/releases/tag/v0.0.45 if you are using the full chart you will need to use https://github.com/zeebe-io/zeebe-full-helm/releases/tag/v0.0.29

**Comment by Zelldon** [comment]
Makes sense thanks @salaboy

**Comment by sebascarra** [comment]
Any sort of way to implement livenessProbes for Zeebe brokers? It is implemented for Zeebe gateways, so I was wondering what's the difference with brokers. Thanks!
