### ISSUE TITLE
Defaults in README.md don't match values.yml

### ISSUE THREAD

**Issue by falko** [zeebe-io/zeebe-cluster-helm#91]
The default JVM options documented in [README.md](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/README.md) don't match the ones in [values.yml](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/values.yaml).

I assume the [README.md](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/README.md) needs updating because we reviewed and discussed [values.yml](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/values.yaml) in PR #82.

**Comment by salaboy** [comment]
fixed
